mdshw5/pyfaidx

pyfaidx/__init__.py
pyfaidx/cli.py

Hey, love pyfaidx so far- really useful and nicely done. I had noticed that in some rare cases, I get a FastaIndexError without any error message, and upon further investigation, I can't get any of your custom errors to display the error message they were called with. I'm using Python 2.7.6 and the most recent version of pyfaidx from pip.
I think the `__init__` constructor for these exceptions is incomplete- you need to call the parent's `__init__` function. But it may not even be necessary for FastaIndexingError, etc- just do 
```python
class FastaIndexingError:
pass
```
for instance, and it will handle the exception message for you when you call it:
```python
>>> raise FastaIndexingError("some error")
FastaIndexingError: some error
```
The pull request makes these changes and passes the …

custom exceptions not showing their error messages

---

pyfaidx/__init__.py

In current implementation a new index file will be created if the index file modification time is older than, or equal, to the fasta file. In some cases, e.g. if the files are downloaded as part of an external bundle, the modification times could be equal for all files. In such cases you often want to preserve the original index.
Fix this by only building index if the index is older than the fasta file. If they have equal mtime, it will be used instead.
The day-to-day reason behind wanting this change is that we're using the reference fasta file from the GATK bundle, and we don't trust to change it from the original bundle index used by GATK. As we don't always have control how the bundle is deployed, touching the index file for each deployment is also a hassle.

Change build_index to only occur for old index

---

.gitignore
README.rst
dev-requirements.txt
pyfaidx/__init__.py
tests/data/download_gene_fasta.py
tests/test_FastaRecord.py

This is just a merge request to allow to return the sequence always as upper case, both in the raw and in the sequence format.
We have this user case in our case.

Allow reference sequence to be returned always as upper case.

---

pyfaidx/__init__.py

Was printing a coordinate to STDOUT on each subset from the Fasta() class.

Remove errant print

---

pyfaidx/__init__.py
tests/test_sequence_class.py

Modify pyfaidx.complement() to work on empty sequences (closes #81), add a test for this case, and use a more efficient implementation of this function.
On my machine, complementing a 55-character string goes from about 3.4us to 800ns with this change.

Fix complement() to work on empty strings, better performance

---

.coveragerc
.gitignore
appveyor.yml
ci/appveyor/vcvars64.bat
dev-requirements.txt
pyfaidx/__init__.py
tests/test_FastaRecord.py
tests/test_feature_indexing.py
tox.ini

The tests for #96 add a new dependency on the 'mock' project for py26, py26, and pypy. You can decide whether it is worth adding that dependency to implement a corner case.
The provided Tox configuration will merge coverage information across multiple test environments, and this required some changes to the coverage configuration in order to merge coverage statistics across multiple instances of the installed 'pyfaidx' package, and it limits coverage reporting to just the 'pyfaidx' package. I'm not sure if that adversely affects how you currently use the coverage report, but if it does the coverage logic can be removed.

Issue #96 and Tox configuration

---

README.rst
pyfaidx/__init__.py
pyfaidx/cli.py

This shouldn't be merged yet, I'm just sending the pr to get feedback / comments and to show something that seems to work. See #77.
To use, compress a FASTA file wtih bgzip (see http://www.htslib.org/doc/tabix.html). Rename the file to have a `.bgz` suffix. You can then create an `.fai` index for that file using the `Faidx` class and read it using the `Fasta` class.
I have a small test index creation file:
```python
#!/usr/bin/env python
from pyfaidx import Faidx
Faidx('data.fasta.bgz')
```
and a text lookup file:
```python
#!/usr/bin/env python
from pyfaidx import Fasta
f = Fasta('data.fasta.bgz')
assert str(f['read-18']) == 'GATGCTGCCACGCTAGGAACGCGCGCTGATAGTTTTCATAATAGAATGTACAAGTGTGTGTTTGCTTTCCTACAAACAGCTCATAAGCCGGAGTCCGCAA'
assert str(f['read-9994']) == …
```

Proof of concept support for BGZF compressed FASTA files.

---

pyfaidx/__init__.py

Initialize lastline so we don't fail on empty FASTA.

---

pyfaidx/cli.py

Added basic support for reverse-complement a sequence automatically, if the start coordinate of a range is larger than the end coordinate.
It is useful, i.e. to directly extract subsequences based on BLAST hit coordinates without dealing with its strandness.

Added basic support for auto reverse-complements

---

pyfaidx/__init__.py

The `Fasta` constructor should not ignore the `build_index` parameter, but pass it to the `Fasta` constructor.

Pass build_index to Fasta constructor

---

pyfaidx/cli.py
tests/test_faidx.py

This PR allows `-v` to be used to negate regular expressions specified by `-g`. This is useful, for example to strip out haplotypes:
```bash
faidx genome.fasta -g "_alt" -v
```

allow -v to be specified alongside -g

---

README.rst

Samtools link previously pointed to tabix instead of bgzip

FIX bgzip link

---

pyfaidx/__init__.py
tests/test_feature_bounds_check.py

Add support for zero-length sequences.
Example FASTA file:
```
>A
ABC
>B
>C
>D
DEF
GH
```
Result: `['ABC', '', '', 'DEFGH']`
Also enables slicing sequences to zero length, which corresponds to slicing python lists:
```python
from pyfaidx import Fasta
a = Fasta('example.fa')[0]
print(a[0:])
print(a[100:]
#>A:101-101
#
```
Please review all the changes, I tested on an example dataset but I cannot be sure that this will always work.

Support zero-length sequences

---

pyfaidx/__init__.py
tests/test_FastaRecord.py

It is a very minor thing, but now `pyfaidx.Fasta` behaves slightly more dictionary-like with `.items` and `.values`.

Fasta more dict-like behaviour

---

.travis.yml
pyfaidx/__init__.py

With the change in `__getitem__`, not the full length of key() is iterated, but just as many elements as necessary.
When at it, `__iter__` calls here avoid the type check by not calling `__getitem__`.
Also, the imports were sorted.
Signed-off-by: Joris Cadow <joriscadow@gmail.com>

Minor improvement in integer indexing Fasta class.

---

pyfaidx/cli.py

Typecast "v" to a str when printing out the "other" nucleotide counts. Code currently throws an error: "TypeError: sequence item 1: expected str instance, int found."

Fix TypeError with faidx --transform nucleotide 

---

.travis.yml
pyfaidx/__init__.py
setup.cfg

This addresses the comment in #174 and mitigates incomplete .fai file creation by first creating a temporary file, and then moving this file after successful creation.

Make FASTA index creation atomic

---

pyfaidx/__init__.py
tests/test_Fasta_synchronization.py

https://github.com/mdshw5/pyfaidx/runs/4982115734?check_suite_focus=true#step:8:45
Using default random.shuffle method which is random.random.

Remove deprecated argument to random.shuffle

---

tests/test_Fasta_bgzip.py
tests/test_faidx.py
tests/test_feature_bounds_check.py
tests/test_feature_indexing.py
tests/test_feature_key_function.py
tests/test_feature_read_ahead_buffer.py
tests/test_feature_sequence_as_raw.py
tests/test_feature_split_char.py
tests/test_sequence_class.py

Hi @mdshw5,
This PR is very much optional. I noticed that you were using `pytest.mark.xfail` to mark tests that raise specific Exceptions. This might be my OCD talking, but it's not the intended usage for xfail, which should be used to mark tests that either fail due to missing implementations or because they are expected to fail due to other reasons: https://docs.pytest.org/en/6.2.x/skipping.html
If the code should raise an Exception due to wrong input or other mistakes it's better to use `pytest.raises`.
In your test-suite it seemed to me that only two tests qualified for being marked as xfail.
Again, this is a very minor distinction. Feel free to close the PR if you prefer using xfail.
Cheers,
Andreas :smiley:

Minor change in pytest xfail usage in tests

---

dev-requirements.txt
pyfaidx/__init__.py
tests/test_fsspec.py

Hi @mdshw5,
I saw that there already was an attempt at implementing `fsspec` support and that the PR is basically stale.
So here's my attempt at implementing fsspec support:
This closes #165 and replaces #168
I explicitly tried to keep the required changes to a minimum, to simplify review.
This follows @manzt recommendations and accepts `fsspec.core.OpenFile` objects.
This can still be done cleaner by refactoring more of `Faidx.__init__`
Tests all pass and I added a single `fsspec` test. Let me know what the best tests would be for covering the base functionality of this library to test `fsspec` support.
Cheers,
Andreas :smiley:

Add fsspec support

---

pyfaidx/__init__.py

Starting with version 1.80, biopython does more stringent checks on opening bgzf files.  This is causing a series of test failures in pyfaidx 0.7.1:
tests/test_Fasta_bgzip.py::test_build_issue_126 XFAIL                    [ 11%]
tests/test_Fasta_bgzip.py::test_integer_slice FAILED                     [ 11%]
tests/test_Fasta_bgzip.py::test_integer_index FAILED                     [ 12%]
tests/test_Fasta_bgzip.py::test_fetch_whole_fasta FAILED                 [ 13%]
tests/test_Fasta_bgzip.py::test_line_len FAILED                          [ 14%]
tests/test_Fasta_bgzip.py::test_mutable_bgzf PASSED                      [ 14%]
tests/test_Fasta_bgzip.py::test_long_names FAILED                        [ 15%]
tests/test_Fasta_bgzip.py::test_fetch_whole_entry FAILED                 [ 16%] …

fix bgzf test failure with biopython 1.80

---

pyfaidx/__init__.py

I'm seeing cases where a Fasta object is garbage collected without Fasta.faidx.file being closed, resulting in a `ResourceWarning: unclosed file <_io.FileIO name='genome.fa' mode='rb' closefd=True>`
This PR fixes the warning in the proper way.
I haven't managed to create a simple test case, but this works in my spaghetti code ;)

fix ResourceWarning: unclosed file

---

pyproject.toml
tests/test_faidx.py
tests/test_feature_indexing.py

This adds setuptools as a package dependency, and tests the version reporting. Fixes #206.

missing setuptools dependency in v0.7.2

---

pyfaidx/__init__.py
pyproject.toml

Try to use importlib from python > 3.8: https://docs.python.org/3/library/importlib.metadata.html#module-importlib.metadata
Otherwise use the installed backport package: https://pypi.org/project/importlib-metadata/
Fix for #212

Replace usage of pkg_resources API

---

pyproject.toml

This dependency fixes the condition where user has biopython installed but the version check does not complete.

Add packaging library for #220

---

pyproject.toml

pyfaidx does not rely on setuptools during day to day operation, so it can be safely removed from the runtime dependencies.
For the rationale, this change originates from the deprecation of the Debian package python3-pkg-resources along the upcoming Python 3.13 reported in [Debian bug #1083691].  For short, python3-pkg-resources happens to be pulled by the packaging tools when runtime dependency on setuptools is declared.
[Debian bug #1083691]: https://bugs.debian.org/1083691

remove setuptools from runtime dependencies

---

pyproject.toml

Hi,
This patch was included as a last-minute cleanup for Debian Trixie.
Greetings

do not needlessly require importlib_metadata

---

pyfaidx/__init__.py

Currently, for remote files (fsspec objects), there is support for pre-computed .fai files, but no support for pre-computed .gzi files. This means that the entire file must be read to re-compute the .fai file as well as the .gzi file (looks like this was re-computation of the index was added recently https://github.com/mdshw5/pyfaidx/pull/164) 
I have implemented the .gzi support in a similar fashion to the .fai support. All of the tests pass, and I created all combinations of local/remote with the following code:
```python
import s3fs
from itertools import product
from fsspec.core import OpenFile
import pyfaidx
fs = s3fs.S3FileSystem()
files_local_and_remote = [
(
"/local/ercc.fa.gz",
"s3://.../ercc.fa.gz",
),
(
"/local/ercc.fa.gz.fai",
"s3://.../ercc.fa.gz.fai",
),
( …
```

feat: Add bgzip index support for fsspec objects
